// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytic/expenses/dates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "Expenses analytic for dates",
                "parameters": [
                    {
                        "enum": [
                            "month",
                            "day"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "Date unit",
                        "name": "unit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "absolute",
                            "cumulative"
                        ],
                        "type": "string",
                        "default": "absolute",
                        "description": "Calculation type",
                        "name": "calculation",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AnalyticResponse"
                            }
                        }
                    }
                }
            }
        },
        "/analytic/expenses/groups": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "expenses"
                ],
                "summary": "Expenses analytic for groups",
                "parameters": [
                    {
                        "enum": [
                            "category",
                            "merchant"
                        ],
                        "type": "string",
                        "default": "category",
                        "description": "Grouping field",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AnalyticResponse"
                            }
                        }
                    }
                }
            }
        },
        "/analytic/income/dates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "income"
                ],
                "summary": "Income analytic for dates",
                "parameters": [
                    {
                        "enum": [
                            "month",
                            "day"
                        ],
                        "type": "string",
                        "default": "month",
                        "description": "Date unit",
                        "name": "unit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AnalyticResponse"
                            }
                        }
                    }
                }
            }
        },
        "/analytic/income/groups": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "income"
                ],
                "summary": "Income analytic for groups",
                "parameters": [
                    {
                        "enum": [
                            "category",
                            "merchant"
                        ],
                        "type": "string",
                        "default": "category",
                        "description": "Grouping field",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.AnalyticResponse"
                            }
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Retrieve transactions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TransactionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Retrieve transaction details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TransactionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AnalyticGroup": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.AnalyticResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AnalyticGroup"
                    }
                }
            }
        },
        "model.TransactionResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "datetime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "merchant": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Transactions Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
