definitions:
  model.Statistics:
    properties:
      amount:
        type: number
      count:
        type: integer
      groups:
        items:
          $ref: '#/definitions/model.StatisticsGroup'
        type: array
    type: object
  model.StatisticsGroup:
    properties:
      amount:
        type: number
      count:
        type: integer
      name:
        type: string
    type: object
  model.StatisticsResponse:
    properties:
      expenses:
        $ref: '#/definitions/model.Statistics'
      income:
        $ref: '#/definitions/model.Statistics'
    type: object
  model.TransactionResponse:
    properties:
      amount:
        type: number
      category:
        type: string
      datetime:
        type: string
      id:
        type: string
      merchant:
        type: string
    type: object
info:
  contact: {}
  title: Transactions Service API
  version: "1.0"
paths:
  /statistics/{by}:
    get:
      parameters:
      - description: Report grouped by
        enum:
        - category
        - merchant
        in: path
        name: by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.StatisticsResponse'
            type: array
      summary: Retrieve transactions statistics by category
      tags:
      - transaction
      - statistics
  /transactions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TransactionResponse'
            type: array
      summary: Retrieve transactions
      tags:
      - transaction
  /transactions/{id}:
    get:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TransactionResponse'
      summary: Retrieve transaction details
      tags:
      - transaction
swagger: "2.0"
