definitions:
  model.TransactionResponse:
    properties:
      amount:
        type: number
      category:
        type: string
      datetime:
        type: string
      id:
        type: string
      merchant:
        type: string
    type: object
info:
  contact: {}
  title: Transactions Service API
  version: "1.0"
paths:
  /transactions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TransactionResponse'
            type: array
      summary: Retrieve transactions
      tags:
      - transaction
  /transactions/{id}:
    get:
      parameters:
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TransactionResponse'
      summary: Retrieve transaction details
      tags:
      - transaction
swagger: "2.0"
